Added a few more action files

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -3836,7 +3836,7 @@ echo "${ECHO_T}no" >&6
 
 fi;
 
-ac_config_files="$ac_config_files Makefile src/Makefile data/Makefile data/styles/Makefile data/backgrounds/Makefile"
+ac_config_files="$ac_config_files Makefile src/Makefile data/Makefile data/actions/Makefile data/styles/Makefile data/backgrounds/Makefile"
 cat >confcache <<\_ACEOF
 # This file is a shell script that caches the results of configure
 # tests run on this system so they can be shared between configure
@@ -4136,16 +4136,17 @@ Try \`$0 --help' for more information." >&2;}
   'Makefile' ) CONFIG_FILES="$CONFIG_FILES Makefile" ;;
   'src/Makefile' ) CONFIG_FILES="$CONFIG_FILES src/Makefile" ;;
   'data/Makefile' ) CONFIG_FILES="$CONFIG_FILES data/Makefile" ;;
+  'data/actions/Makefile' ) CONFIG_FILES="$CONFIG_FILES data/actions/Makefile" ;;
   'data/styles/Makefile' ) CONFIG_FILES="$CONFIG_FILES data/styles/Makefile" ;;
   'data/backgrounds/Makefile' ) CONFIG_FILES="$CONFIG_FILES data/backgrounds/Makefile" ;;
 
   # This is an error.
-  -*) { { echo "$as_me:4143: error: unrecognized option: $1
+  -*) { { echo "$as_me:4144: error: unrecognized option: $1
 Try \`$0 --help' for more information." >&5
 echo "$as_me: error: unrecognized option: $1
 Try \`$0 --help' for more information." >&2;}
    { (exit 1); exit 1; }; } ;;
-  *) { { echo "$as_me:4148: error: invalid argument: $1" >&5
+  *) { { echo "$as_me:4149: error: invalid argument: $1" >&5
 echo "$as_me: error: invalid argument: $1" >&2;}
    { (exit 1); exit 1; }; };;
   esac
@@ -4383,7 +4384,7 @@ done; }
   esac
 
   if test x"$ac_file" != x-; then
-    { echo "$as_me:4386: creating $ac_file" >&5
+    { echo "$as_me:4387: creating $ac_file" >&5
 echo "$as_me: creating $ac_file" >&6;}
     rm -f "$ac_file"
   fi
@@ -4401,7 +4402,7 @@ echo "$as_me: creating $ac_file" >&6;}
       -) echo $tmp/stdin ;;
       [\\/$]*)
          # Absolute (can't be DOS-style, as IFS=:)
-         test -f "$f" || { { echo "$as_me:4404: error: cannot find input file: $f" >&5
+         test -f "$f" || { { echo "$as_me:4405: error: cannot find input file: $f" >&5
 echo "$as_me: error: cannot find input file: $f" >&2;}
    { (exit 1); exit 1; }; }
          echo $f;;
@@ -4414,7 +4415,7 @@ echo "$as_me: error: cannot find input file: $f" >&2;}
            echo $srcdir/$f
          else
            # /dev/null tree
-           { { echo "$as_me:4417: error: cannot find input file: $f" >&5
+           { { echo "$as_me:4418: error: cannot find input file: $f" >&5
 echo "$as_me: error: cannot find input file: $f" >&2;}
    { (exit 1); exit 1; }; }
          fi;;
