Redone translucancy support, reconstruction of WaWindow & WaChildWindow classes.

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -4593,7 +4593,6 @@ fi
 LIBS="$LIBS $Imlib2_lib"
 
 ac_config_files="$ac_config_files Makefile src/Makefile data/Makefile data/actions/Makefile data/styles/Makefile data/backgrounds/Makefile doc/Makefile"
-
 cat >confcache <<\_ACEOF
 # This file is a shell script that caches the results of configure
 # tests run on this system so they can be shared between configure
@@ -4703,7 +4702,7 @@ rm -f confdef2opt.sed
 : ${CONFIG_STATUS=./config.status}
 ac_clean_files_save=$ac_clean_files
 ac_clean_files="$ac_clean_files $CONFIG_STATUS"
-{ echo "$as_me:4706: creating $CONFIG_STATUS" >&5
+{ echo "$as_me:4705: creating $CONFIG_STATUS" >&5
 echo "$as_me: creating $CONFIG_STATUS" >&6;}
 cat >$CONFIG_STATUS <<_ACEOF
 #! $SHELL
@@ -4871,7 +4870,7 @@ cat >>$CONFIG_STATUS <<\EOF
     echo "$ac_cs_version"; exit 0 ;;
   --he | --h)
     # Conflict between --help and --header
-    { { echo "$as_me:4874: error: ambiguous option: $1
+    { { echo "$as_me:4873: error: ambiguous option: $1
 Try \`$0 --help' for more information." >&5
 echo "$as_me: error: ambiguous option: $1
 Try \`$0 --help' for more information." >&2;}
@@ -4899,12 +4898,12 @@ Try \`$0 --help' for more information." >&2;}
   'doc/Makefile' ) CONFIG_FILES="$CONFIG_FILES doc/Makefile" ;;
 
   # This is an error.
-  -*) { { echo "$as_me:4902: error: unrecognized option: $1
+  -*) { { echo "$as_me:4901: error: unrecognized option: $1
 Try \`$0 --help' for more information." >&5
 echo "$as_me: error: unrecognized option: $1
 Try \`$0 --help' for more information." >&2;}
    { (exit 1); exit 1; }; } ;;
-  *) { { echo "$as_me:4907: error: invalid argument: $1" >&5
+  *) { { echo "$as_me:4906: error: invalid argument: $1" >&5
 echo "$as_me: error: invalid argument: $1" >&2;}
    { (exit 1); exit 1; }; };;
   esac
@@ -5146,7 +5145,7 @@ done; }
   esac
 
   if test x"$ac_file" != x-; then
-    { echo "$as_me:5149: creating $ac_file" >&5
+    { echo "$as_me:5148: creating $ac_file" >&5
 echo "$as_me: creating $ac_file" >&6;}
     rm -f "$ac_file"
   fi
@@ -5164,7 +5163,7 @@ echo "$as_me: creating $ac_file" >&6;}
       -) echo $tmp/stdin ;;
       [\\/$]*)
          # Absolute (can't be DOS-style, as IFS=:)
-         test -f "$f" || { { echo "$as_me:5167: error: cannot find input file: $f" >&5
+         test -f "$f" || { { echo "$as_me:5166: error: cannot find input file: $f" >&5
 echo "$as_me: error: cannot find input file: $f" >&2;}
    { (exit 1); exit 1; }; }
          echo $f;;
@@ -5177,7 +5176,7 @@ echo "$as_me: error: cannot find input file: $f" >&2;}
            echo $srcdir/$f
          else
            # /dev/null tree
-           { { echo "$as_me:5180: error: cannot find input file: $f" >&5
+           { { echo "$as_me:5179: error: cannot find input file: $f" >&5
 echo "$as_me: error: cannot find input file: $f" >&2;}
    { (exit 1); exit 1; }; }
          fi;;
